[features]
seeds = false
skip-lint = false
[programs.localnet]
crud_anchor_v2 = "GD6s6jBdxFf7pbvxx87uPQmvNYKuVXGfiziJCVkFmE2F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/vietvo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
